#!/bin/sh

# Detect resolution
xRes=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
yRes=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

if [ ${xRes} == 1920 ] ; then 
    TOP_PADDING=25
    BOTTOM_PADDING=70
else #high res
    TOP_PADDING=75
    BOTTOM_PADDING=100
fi

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# wallpaper
nitrogen --restore &

# launch compton
al-compositor --start &

# xfce settings
xfsettingsd &

# panel
al-polybar-session &

# Set some bsp specific stuff
bspc monitor -d I II III IV V

bspc config border_width 2
bspc config window_gap 12
bspc config top_padding ${TOP_PADDING}
bspc config right_padding 0
bspc config bottom_padding ${BOTTOM_PADDING}
bspc config left_padding 0

bspc config -d ^2 window_gap 0

bspc config -d ^3 window_gap 0

bspc config split_ratio 0.54
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true

bspc config focused_border_color  "#98c479"
bspc config normal_border_color "#282c34"

bspc config pointer_modifier mod4
bspc config click_to_focus true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a thunar state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a Inkscape state=fullscreen focus=on

# plank
plank &

# fix for java apps
wmname LG3D

